# Dependencies
# - markdown:         redcarpet
highlighter:      pygments

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Setup
# - title:            '[TITLE]'
# - tagline:          'A Jekyll theme'
# - description:      "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
# - url:              "http://[HOSTNAME]"
# - base# - url:          "[PATH]"
# - user# - name: "[USERNAME]"

# - author:
  # - name:           'Mark Otto'
  # - url:            https://twitter.com/mdo

# - paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Chad Moore"
tagline: ""
description: "Follow <a href=\"https://micro.blog/cm\">@cm on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/cm\">@cm on Micro.blog</a>."
baseurl: ""
url: "http://techartjam.com"
markdown: "kramdown"
username: "cm"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Chad Moore"
name: "Chad Moore"
gravatar_hash: "5648eb4afeea809a537cb193a3e6392c"
avatar: "https://www.gravatar.com/avatar/5648eb4afeea809a537cb193a3e6392c?s=160"
full_name: "Chad Moore"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"